### PR TITLE
Adds sbt-microsites Plugin and UI Resources

### PR DESCRIPTION
**Pull request by juanpedromoreno**
Please, @raulraja @rafaparadela @israelperezglez could you review?

If you want to test locally you need [Jekyll](https://jekyllrb.com/) locally, depending on your platform, you might do this with:

```bash
yum install jekyll

apt-get install jekyll

gem install jekyll
```

Once you have installed it, you could perform the following steps:

* Build the microsite:

```bash
sbt "project docs" "clean" "makeMicrosite"
```

* Then, to visualize the website in your browser, in a shell, navigate to the generated site directory in `docs/target/site`
* Start jekyll with `jekyll serve`
* Navigate to http://localhost:4000/cats/

Thanks!

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
Microsite look&feel:

cats

**Comment by raulraja** [comment]
Does the Travis file need to be updated too?

**Comment by juanpedromoreno** [comment]
I'm not sure what you mean. Could you point me out to the file or place that you mean. Thanks!

**Comment by raulraja** [comment]
Thought they were auto updating docs on each master merge https://github.com/47deg/cats/blob/master/scripts/travis-publish.sh
But doesn't look like it.

**Comment by raulraja** [comment]
I'm on the road but so far what I've seen looks good. Can't load the site locally on my phone so if you need a quick revision someone else should give you the LGTM

**Comment by franciscodr** [comment]
LGTM

**Pull request merged**
